# Use official slim Python 3.11 image as base
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy dashboard code and app package
COPY ./dashboard ./dashboard
COPY ./app ./app

# Expose Streamlit default port
EXPOSE 8501

# Command to launch Streamlit application
CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
