services:
  - type: web
    name: agentic-ai-crm-api
    env: docker
    dockerfilePath: Dockerfile.api
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: agentic-ai-crm-ui
    env: docker
    dockerfilePath: Dockerfile.dashboard
    plan: free
    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: agentic-ai-crm-api
          property: host
