from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from app.db.session import get_db
from app.services.audit_service import AuditService
from app.core.security import SecurityAlertService

router = APIRouter(prefix="/audit", tags=["Audit & Security Governance"])

@router.get("/logs")
def get_audit_logs(
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    allowed: Optional[bool] = None,
    agent_id: Optional[str] = None,
    db: Session = Depends(get_db)
):
    """Retrieve audit log entries with optional filters for status (allowed/blocked) and agent ID."""
    logs = AuditService.get_logs(
        db,
        limit=limit,
        offset=offset,
        allowed_filter=allowed,
        agent_id_filter=agent_id
    )
    return {
        "count": len(logs),
        "limit": limit,
        "offset": offset,
        "logs": [
            {
                "id": log.id,
                "timestamp": log.timestamp.isoformat(),
                "agent_id": log.agent_id,
                "tool_name": log.tool_name,
                "operation": log.operation,
                "target_customer_id": log.target_customer_id,
                "allowed": log.allowed,
                "reason": log.reason
            }
            for log in logs
        ]
    }

@router.get("/stats")
def get_audit_stats(db: Session = Depends(get_db)):
    """Retrieve high-level governance metrics for dashboard presentation."""
    return AuditService.get_audit_statistics(db)

@router.get("/alerts")
def get_security_alerts(active_only: bool = False, db: Session = Depends(get_db)):
    """Retrieve active and historical threat alerts generated by rogue agents."""
    alerts = SecurityAlertService.get_alerts(db, active_only=active_only)
    return {
        "count": len(alerts),
        "alerts": [
            {
                "id": alert.id,
                "timestamp": alert.timestamp.isoformat(),
                "agent_id": alert.agent_id,
                "reason": alert.reason,
                "total_blocked_count": alert.total_blocked_count,
                "is_active": alert.is_active
            }
            for alert in alerts
        ]
    }
